[package]
name = "filter-parser"
version = "1.0.0"
edition = "2021"
description = "The parser for the Meilisearch filter syntax"
publish = false

[dependencies]
nom = "7.1.3"
nom_locate = "4.1.0"

[dev-dependencies]
insta = "1.26.0"
